# This docker-compose was attempt to build/run test container
version: "3"
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev # different name; -f parameter
        ports: 
            - "3000:3000" #Port mapping
        volumes: 
            - /app/node_modules # Exlcude from override
            - .:/app # Copy local dir to app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm","run","test"] # This will override the starting command in Dockerfile.dev

        
